os: linux
dist: xenial

language: python

jobs:
  include:
    - name: Python 3.6 on Xenial Linux
      python: 3.6
    - name: Python 3.7 on Xenial Linux
      python: 3.7
    - name: Python 3.8 on Xenial Linux
      python: 3.8
    - name: Python 3.6 on Bionic Linux
      dist: bionic
      python: 3.6
    - name: Python 3.7 on Bionic Linux
      dist: bionic
      python: 3.7
    - name: Python 3.8 on Bionic Linux
      dist: bionic
      python: 3.8
    - name: Python 3.6 on Focal Linux
      dist: focal
      python: 3.6
    - name: Python 3.7 on Focal Linux
      dist: focal
      python: 3.7
    - name: Python 3.8 on Focal Linux
      dist: focal
      python: 3.8
      env: DEPLOY_AT_THIS_ENV=true

    - name: Python 3.7 on macOS 10.14
      os: osx
      osx_image: xcode11.3
      language: shell
    - name: Python 3.8 on macOS 10.14
      os: osx
      osx_image: xcode11.3
      language: shell
      env: PATH=/usr/local/opt/python@3.8/bin:$PATH
    - name: Python 3.7 on macOS 10.15
      os: osx
      osx_image: xcode12.2
      language: shell
    - name: Python 3.8 on macOS 10.15
      os: osx
      osx_image: xcode12.2
      language: shell
      env: PATH=/usr/local/opt/python@3.8/bin:$PATH

    - name: Python 3.6 on Windows
      os: windows
      language: shell
      before_install: choco install python --version 3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: Python 3.7 on Windows
      os: windows
      language: shell
      before_install: choco install python --version 3.7.9
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: Python 3.8 on Windows
      os: windows
      language: shell
      before_install: choco install python --version 3.8.6
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: Python 3.9 on Windows
      os: windows
      language: shell
      before_install: choco install python --version 3.9.0
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

install:
  - pip3 install --upgrade setuptools coveralls flake8 yapf isort
  - pip3 install -e .

before_script:
  - isort --df nncore/ tests/ examples/ setup.py
  - yapf -r -d nncore/ tests/ examples/ setup.py
  - flake8 nncore/ tests/ examples/ setup.py

script:
  - coverage run --source=nncore setup.py test

after_success:
  - coveralls

deploy:
  provider: pypi
  username: __token__
  password:
    secure: FpqtAv6eSP/XQdaRDZvjEraAzBXvUoWGzNDzanAJ/z9EFXVi1S0faRsAFVTVaOr2jowGIFySzJRtvSf72+KtlKe70LdNI4YWM8YVu0j66O+xXFUAauQz1kcMR5tGw2d4gJDf5Xuzd5qToJWYj0F02KOMsmbOlsYHEaScRKC8LVMQ04NLcJUPHTkL/7oCq66fFCIUVXu9HgbeQfnovMPEu9iL3LWVEKHDoEwIREPvApychFWFGqZetql9g5qdPy0eElRqz9EyFtTnWvgo/mzY9F7IdnzZ0h/ThxrQsCj6pbz+AuKiiAB/n8m6LBQfWxpqQ4vEZOyhqa54+2DujSirmgsmuO+rIBtzuxi0b/sdry5bDH+B0uk5NqSxH8LnnYCg0gc9fmPFA0CXEEAZtQOQye4L8dv5Hfsl2X3T7IPN+AG1i8j0g4OcfLrv3en8NhvP5asNbOvhn8iG15MbYqk8/TPry0Omj8dfEps03IT3zwa0WZ8iwz8ZlD0ngrAj8EJQROCa8v5iZYjG/17+wYeqvYw6NkBM6xn227hhG+ZMIwXjSsx4y4xUEa9Qdr7Z4t5WN8YZIGRiazRMXXvHGj2xUcTqy2lxaQHfXZxdenNGnnSJ+R9C1Fe+zBnmnnE7GiwPw+KiPVg1UxaggLhi/txcxt6DqCLB85MNagF1lzD7c1Q=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    branch: release
    tags: true
    python: 3.8
    condition: $DEPLOY_AT_THIS_ENV

notifications:
  slack:
    secure: yHyS813GCevoo4IsM5Y/l3N2fXG74WCVLZaaGItJEvAsY7T80aQC9ZrszoRq8ElHpLtu1sZ+mwKTFSdDYicDoJnLL0dITsGDruoXZ1zoK2Yw3rJKVRBuMUvr6ITP6NMOuD5mfG9tbmS0mt7dD1YbATxtgG4V9FqbMTczCKOhwHZwfADI4a5LblQOAFw6CCQ+OTq12jgunXnl5d2KmmMGzIM5QeoUqzSjV4W2sMYWctpx7O6r5WQCj/374O2O2Ay1zyUZfD8K+xa1UaNTw83jK9HFbyKPUMLAHBQlHbTDXSOA7Ey65pri5TAGa28S9EqQiNhNKluP7BXvDd6yFyOU1klwNbisa9egeLa1GlPNuHR7O7BNF2ffBWVrEau1XCysJ5zadSOsEsBPnKBe5mqiSQ57+1zH1StcbVtBhZHPKP7u0wzyXNMkm47i4Vx58ofzqsxz+UZSz9VdEcgYT0WPeJPakMyWtwZBHQT0AGFx2ZVkiAQSOMUmFXuajBsJ5Q4HvvpW7o67FW3Ax5+GOM1f9GDuVrJQPBeXhh8sX8IH7fh+ggUvXRkVliSdaSvg6tT3EsDZOkSBF2ni/H4h26WPW4n0rwf3/pF8Vi4TXmpp1dMdgvCNLEXEk2rmipvi75oj2jcM/qqTRsFtbQDcApefgpKxvHSjf4K41tUZvd6fkB4=
