name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-2022]
        python: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install requirements
      run: pip install --upgrade setuptools wheel isort yapf flake8 coverage coveralls
    - name: Check code style
      run: |
        isort --df nncore/ tests/ examples/ setup.py
        yapf -dr nncore/ tests/ examples/ setup.py
        flake8 nncore/ tests/ examples/ setup.py
    - name: Install NNCore
      run: pip install -e .
    - name: Run unit tests
      run: coverage run --source=nncore setup.py test
    - name: Report coverage
      run: coverage report
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: coveralls
